version: "3.9"

x-common-variables: &common-variables
  COSMOSDB_CONNECTION_STRING: mongodb://testUsername:testPassword@database:27017
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

services:
  mongo:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: events
      MONGO_INITDB_ROOT_USERNAME: testUsername
      MONGO_INITDB_ROOT_PASSWORD: testPassword

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testUsername
      ME_CONFIG_MONGODB_ADMINPASSWORD: testPassword
      ME_CONFIG_MONGODB_SERVER: mongo


  discovery-server:
    build: ./discovery-server
    image: discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      <<: *common-variables

  api-gateway:
    build: ./gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8085:8085"
    links:
      - discovery-server
    depends_on:
      - discovery-server
    environment:
      <<: *common-variables

  product-service:
    build: ./product-service

    image: product-service:latest
    container_name: product-service
    ports:
      - "7071:7071"
    links:
      - discovery-server
      - mongo
    depends_on:
      - api-gateway
      - discovery-server
    environment:
      <<: *common-variables

  order-service:
    build: ./order-service

    image: order-service:latest
    container_name: order-service
    ports:
      - "7072:7072"
    links:
      - discovery-server
      - mongo
    depends_on:
      - api-gateway
      - discovery-server
    environment:
      <<: *common-variables

  user-service:
    build: ./user-service

    image: user-service:latest
    container_name: user-service
    ports:
      - "7070:7070"
    links:
      - discovery-server
      - mongo
    depends_on:
      - api-gateway
      - discovery-server
    environment:
      <<: *common-variables

