version: "3.9"

services:
  mongo:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: events
      MONGO_INITDB_ROOT_USERNAME: testUsername
      MONGO_INITDB_ROOT_PASSWORD: testPassword

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testUsername
      ME_CONFIG_MONGODB_ADMINPASSWORD: testPassword
      ME_CONFIG_MONGODB_SERVER: mongo