server:
  port: 8761

spring:
  application:
    name: discovery-server
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
