spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: ${COSMOSDB_CONNECTION_STRING:mongodb://testUsername:testPassword@localhost:27017}
      authentication-database: admin
      database: DBproducts


eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
server:
  port: 7071